language: cpp

dist: trusty

compiler:  
    - gcc
    - clang

before_install:
    - sudo apt-get update -qq -y
    - sudo apt-get install libassimp-dev
    - sudo apt-get install libfreeimage-dev

before_script:  
    - mkdir build
    - cd build
    - cmake ..

script: make  
