image: Visual Studio 2015

matrix:
    fast_finish: true


cache: c:\tools\vcpkg\installed\

install:
- cd C:\Tools\vcpkg
- git pull
- .\bootstrap-vcpkg.bat
- vcpkg install assimp:x86-windows
- vcpkg install freeimage:x86-windows
- vcpkg integrate install
- cd %APPVEYOR_BUILD_FOLDER%

clone_script:
  - cmd: >-
      git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
      && cd %APPVEYOR_BUILD_FOLDER%
      && git checkout -qf %APPVEYOR_REPO_COMMIT%
      && git submodule update --init --recursive

before_build:
    - mkdir build
    - cd build
    - cmake -G "Visual Studio 14 2015" -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake ..

build_script: cmake --build .
